//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/ProgressBarInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ProgressBarInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ProgressBarInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ProgressBarInputAction"",
    ""maps"": [
        {
            ""name"": ""ProgressBar"",
            ""id"": ""a9c4fb58-4d75-4343-a850-e560cda71069"",
            ""actions"": [
                {
                    ""name"": ""Bar"",
                    ""type"": ""Button"",
                    ""id"": ""98096fb8-3416-4837-8854-368a6af5a375"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4f95db14-56cf-4b20-b5ec-75acb7f55b1e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold(duration=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ProgressBar
        m_ProgressBar = asset.FindActionMap("ProgressBar", throwIfNotFound: true);
        m_ProgressBar_Bar = m_ProgressBar.FindAction("Bar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ProgressBar
    private readonly InputActionMap m_ProgressBar;
    private IProgressBarActions m_ProgressBarActionsCallbackInterface;
    private readonly InputAction m_ProgressBar_Bar;
    public struct ProgressBarActions
    {
        private @ProgressBarInputAction m_Wrapper;
        public ProgressBarActions(@ProgressBarInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Bar => m_Wrapper.m_ProgressBar_Bar;
        public InputActionMap Get() { return m_Wrapper.m_ProgressBar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProgressBarActions set) { return set.Get(); }
        public void SetCallbacks(IProgressBarActions instance)
        {
            if (m_Wrapper.m_ProgressBarActionsCallbackInterface != null)
            {
                @Bar.started -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnBar;
                @Bar.performed -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnBar;
                @Bar.canceled -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnBar;
            }
            m_Wrapper.m_ProgressBarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Bar.started += instance.OnBar;
                @Bar.performed += instance.OnBar;
                @Bar.canceled += instance.OnBar;
            }
        }
    }
    public ProgressBarActions @ProgressBar => new ProgressBarActions(this);
    public interface IProgressBarActions
    {
        void OnBar(InputAction.CallbackContext context);
    }
}
